### PR TITLE
New end-to-end sample for Serverless Web Application Architecture

### PR DESCRIPTION
**Pull request by wviriya**
Full sample can be found on https://github.com/Azure-Samples/serverless-web-application

### CODE REVIEW

**Comment by wviriya** [comment]
@N-Usha this is a new sample that I have been working on. It is now completed. I'm just not sure where this belong to, so I created a folder for End-to-End for complete architecture samples.

**Comment by vermegi** [comment]
@wviriya looks really good. 
I think some edits on the main readme are also needed for this, but let's have @N-Usha decide on that and what it should look like.

**Comment by ralarcon** [comment]
We have reviewed this PR with the Azure Functions team and they are OK with it. We can go ahead and merge it unles @pulkitaggarwl or @N-Usha have any other comments.

**Comment by kaverma** [comment]
The changes look good to me. Adding @N-Usha also to review.

**Comment by kaverma** [comment]
Do we need to update in https://github.com/Azure/actions-workflow-samples/edit/master/README.md as well for the new sample?

**Review by kaverma — APPROVED** [review]

**Comment by ralarcon** [comment]
@kaverma, Yes... I would suggest to add a new entry to https://github.com/Azure/actions-workflow-samples/edit/master/README.md, "/Azure API Management". Other option is to add it under "/Functions" where ever you prefer.

@N-Usha, have a look and give your thoughts? Hopefully, we can have this ready by mid-this week. 

Thanks!

**Comment by kaverma** [comment]
> @kaverma, Yes... I would suggest to add a new entry to https://github.com/Azure/actions-workflow-samples/edit/master/README.md, "/Azure API Management". Other option is to add it under "/Functions" where ever you prefer.
> 
Yes, I think we can add under Azure App service

**Comment by ralarcon** [comment]
After having a closer look, not sure if adding directly "API Management" will clear enough. I'm thinking to add the following entry to the "Folder Structure" list:

- [**/End-to-End/Serverless**](/End-to-End/Serverless-web-application) Sample to deploy and manage the lifecycle of a [serverless web application](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app). The application serves static content from Azure Blob Storage, and implements an API using Azure Functions which is exposed through API Management. The API reads data from Cosmos DB and returns the results to the web app.

As we already have the End-to-End folder added in the PR, it will point to the content explaining the end-to-end scenario and routing the users to the sample and the architecture reference which is implementing.

If we want to emphasise the API Management, maybe we can rename "/End-to-End/Serverless-web-application" to "/End-to-End/Serverless-with-API-Management"

@kaverma, what do you think?  

cc/ @wviriya

**Comment by kaverma** [comment]
Hi @ralarcon 

Sure, in [/End-to-End/Serverless](https://github.com/End-to-End/Serverless-web-application) looks good to me.

**Comment by ralarcon** [comment]
@N-Usha, @kaverma, can you merge this PR. Then I will add the modification to the main README.md to point to the sample.

Thanks!

**Comment by ralarcon** [comment]
@N-Usha, @kaverma, Just for me to understand. Are you waiting to have the change in the main README.md to *merge* the PR?

If so, @wviriya can you add the change to the PR. Basically the content is:

[/End-to-End/Serverless](https://github.com/End-to-End/Serverless-web-application) Sample to deploy and manage the lifecycle of a [serverless web application](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app). The application serves static content from Azure Blob Storage, and implements an API using Azure Functions which is exposed through API Management. The API reads data from Cosmos DB and returns the results to the web app.

If not, please *merge* the PR and then I'll do the README change.

**Comment by kaverma** [comment]
Hi @ralarcon, it will be great if Azure web app team can also review and approve the changes. @kulkarnisonia16 , can you please have a look?

**Comment by ralarcon** [comment]
> Hi @ralarcon, it will be great if Azure web app/ functions team can also review and approve the changes. @kulkarnisonia16, @santhoshsram , can you please have a look?

@kulkarnisonia16 and his team already reviewed with us the sample with us and we got their OK. @kulkarnisonia16, could you approve the changes in this PR so we can go ahead?

Not sure if @santhoshsram did the chance to have a look too. If possible, please, have a look and give your thoughts.

**Review by kulkarnisonia16 — APPROVED** [review]

**Comment by kaverma** [comment]
Thanks @kulkarnisonia16, please go ahead and merge if no more reviews are required from Azure end. From Actions perspective I have reviewed. Thanks.

**Comment by ralarcon** [comment]
> Thanks @kulkarnisonia16, please merge this change if no more reviews are required from Azure end. From Actions perspective I have reviewed. Thanks.

I'm not able to merge... so, please, anyone with permission to merge, go ahead as it has been reviewed and is ready to merge.

**Comment by ralarcon** [comment]
#sign-off

**Pull request merged**
